# Generated by Django 5.1.4 on 2025-09-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(upload_to='product-files/'),
        ),
    ]
