# Generated by Django 5.1.7 on 2025-09-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='creater',
            field=models.CharField(default=1, max_length=200, verbose_name='Создатель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images', verbose_name='Изображения'),
        ),
    ]
