# Generated by Django 5.1.4 on 2025-10-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
