# Generated by Django 5.1.7 on 2025-09-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellers',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True),
        ),
    ]
